# Required
version: 2

build:
  os: ubuntu-lts-latest
  commands:
    - asdf plugin add pixi
    - asdf install pixi latest
    - asdf global pixi latest
    - pixi run build-docs
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r docs/_build/html/** $READTHEDOCS_OUTPUT/html/

formats: all

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
