# Required
version: 2

build:
  os: windows-latest
  commands:
    - asdf plugin add pixi
    - asdf install pixi latest
    - asdf global pixi latest
    - pixi install -e docs
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - pixi run build-docs $READTHEDOCS_OUTPUT/html/

formats: all

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false
